### PR TITLE
Update expo-linear-gradient and react-native-reanimated

### PR DESCRIPTION
**Pull request by jedahan**
### Identify the Bug

Link to the issue describing the bug that you're fixing.

https://github.com/alexZajac/react-native-skeleton-content/issues/33

### Description of the Change

I just removed package-lock.json and did `npm install`

### Alternate Designs

Not sure what alternate designs there are

### Possible Drawbacks

If a package update other than expo-linear-gradient has a breaking change

### Verification Process

What process did you follow to verify that the change has not introduced any regressions? 
I published this fork and ran it in our own project.
Tests pass.

### Release Notes

Please describe the changes in a single line that explains this improvement in
terms that a user can understand.

- Updated dependencies.

### CODE REVIEW

**Comment by alexZajac** [comment]
Hi, I removed the `node_modules` folder and regenerated a lock file, could you try with the newest version of the package?

**Comment by bombillazo** [comment]
Any update on this PR?

**Comment by jedahan** [comment]
I dont think this is the best solution, we should close it once #43 is re-opened and addressed.

**Comment by bombillazo** [comment]
> 
> 
> I dont think this is the best solution, we should close it once #43 is re-opened and addressed.

What exactly is the problem/issue?

**Pull request closed without merging**
